getgenv().UserConfig = {
    ["FPS Cap"] = 5,

    ["Auto Double Or Nothing"] = false,
    ["Double Or Nothing Target Wins"] = 1,

    ["Auto Buy Seed"] = true,
    ["Auto Plant Seed"] = true,
    ["Auto Plant"] = true,
    ["Limit Auto Plant"] = 300,

    ["Blacklist Seed"] = {
        "Rainbow",
        "Gold",
        "Mega",
    },

    ["Blacklist Shovel"] = {
        "Rainbow",
        "Gold",
        "Bloodlit",
        "Electric",
        "Starstruck",
        "Frozen",
        "Aurora",
        "Ignited",
        "Dragon's Breath",
        "Hypno Bloom",
        "Moon Bloom",
        "Venom Spitter",
        "Poison Apple",
        "Pomegranate",
        "Venus Fly Trap",
        "Sunflower",
        "Cherry",
        "Acorn",
        "Ghost Pepper",
        "Briar Rose",
        "Lotus",
        "Poison Ivy",
        "Glow Mushroom",
    },

    ["Shovel Plant Once"] = {},

    ["Limit Plant Seed"] = {
        ["Carrot"] = 40,
        ["Strawberry"] = 80,
        ["Blueberry"] = 80,
        ["Tulip"] = 30,
        ["Tomato"] = 80,
        ["Apple"] = 60,
        ["Bamboo"] = 80,
        ["Corn"] = 80,
        ["Cactus"] = 80,
        ["Pineapple"] = 50,
        ["Mushroom"] = 5,
        ["Green Bean"] = 40,
        ["Banana"] = 50,
        ["Grape"] = 50,
        ["Coconut"] = 50,
        ["Mango"] = 50,
        ["Dragon Fruit"] = 60,
        ["Acorn"] = 80,
        ["Cherry"] = 80,
        ["Sunflower"] = 100,
        ["Venus Fly Trap"] = 120,
        ["Pomegranate"] = 120,
        ["Poison Apple"] = 120,
        ["Venom Spitter"] = 150,
        ["Moon Bloom"] = 200,
        ["Hypno Bloom"] = 200,
        ["Dragon's Breath"] = 200,
    },

    ["Limit Buy Seed"] = {
        ["Carrot"] = 80,
        ["Strawberry"] = 120,
        ["Blueberry"] = 120,
        ["Tulip"] = 50,
        ["Tomato"] = 120,
        ["Apple"] = 80,
        ["Bamboo"] = 200,
        ["Corn"] = 200,
        ["Cactus"] = 200,
        ["Pineapple"] = 100,
        ["Mushroom"] = 20,
        ["Green Bean"] = 100,
        ["Banana"] = 100,
        ["Grape"] = 100,
        ["Coconut"] = 100,
        ["Mango"] = 100,
        ["Dragon Fruit"] = 120,
        ["Acorn"] = 150,
        ["Cherry"] = 150,
        ["Sunflower"] = 200,
        ["Venus Fly Trap"] = 300,
        ["Pomegranate"] = 300,
        ["Poison Apple"] = 300,
        ["Venom Spitter"] = 500,
        ["Moon Bloom"] = 999,
        ["Hypno Bloom"] = 999,
        ["Dragon's Breath"] = 999,
    },

    ["Favorite"] = {
        ["Dragon Fruit"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Acorn"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Cherry"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Sunflower"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Venus Fly Trap"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Pomegranate"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Poison Apple"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Venom Spitter"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Moon Bloom"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Hypno Bloom"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Dragon's Breath"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Ghost Pepper"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Briar Rose"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Romanesco"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Beanstalk"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Lotus"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
    },

    -- Harvest Mutation Only:
    --   {}: Harvest all plants normally.
    --   "PlantName": Only harvest that plant when it has any mutation.
    --   ["PlantName"] = {"Mutation1", "Mutation2"}:
    --       Only harvest that plant when it has one of the listed mutations.
    -- Plants not listed here are always harvested normally.
    -- Example:
    -- ["Harvest Mutation Only"] = {
    --     "Bamboo",
    --     ["Tomato"] = {"Rainbow", "Gold", "Electric"},
    --     "Apple",
    -- },
    ["Harvest Mutation Only"] = {
        -- ["Carrot"] = {"DO_NOT_HARVEST_LOW_VALUE"},
        -- ["Strawberry"] = {"DO_NOT_HARVEST_LOW_VALUE"},
        -- ["Blueberry"] = {"DO_NOT_HARVEST_LOW_VALUE"},
        -- ["Tulip"] = {"DO_NOT_HARVEST_LOW_VALUE"},
        -- ["Tomato"] = {"DO_NOT_HARVEST_LOW_VALUE"},
        -- ["Apple"] = {"DO_NOT_HARVEST_LOW_VALUE"},
        -- ["Bamboo"] = {"DO_NOT_HARVEST_LOW_VALUE"},
        -- ["Corn"] = {"DO_NOT_HARVEST_LOW_VALUE"},
        -- ["Cactus"] = {"DO_NOT_HARVEST_LOW_VALUE"},
        -- ["Pineapple"] = {"DO_NOT_HARVEST_LOW_VALUE"},
        -- ["Green Bean"] = {"DO_NOT_HARVEST_LOW_VALUE"},
        -- ["Banana"] = {"DO_NOT_HARVEST_LOW_VALUE"},
        -- ["Grape"] = {"DO_NOT_HARVEST_LOW_VALUE"},
        -- ["Coconut"] = {"DO_NOT_HARVEST_LOW_VALUE"},
        -- ["Mango"] = {"DO_NOT_HARVEST_LOW_VALUE"},
        -- ["Baby Cactus"] = {"DO_NOT_HARVEST_LOW_VALUE"},
        -- ["Horned Melon"] = {"DO_NOT_HARVEST_LOW_VALUE"},
        -- ["Pumpkin"] = {"DO_NOT_HARVEST_LOW_VALUE"},
        -- ["Thorn Rose"] = {"DO_NOT_HARVEST_LOW_VALUE"},

        ["Mushroom"] = {"Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Dragon Fruit"] = {"Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Acorn"] = {"Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Cherry"] = {"Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Sunflower"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Venus Fly Trap"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Pomegranate"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Poison Apple"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Venom Spitter"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Moon Bloom"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Hypno Bloom"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Dragon's Breath"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Glow Mushroom"] = {"Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Poison Ivy"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Ghost Pepper"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Briar Rose"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Romanesco"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Beanstalk"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
        ["Lotus"] = {"Gold", "Rainbow", "Bloodlit", "Electric", "Starstruck", "Frozen", "Aurora", "Ignited"},
    },

    ["Buy Pets"] = {
        ["Bunny"] = 6,
        ["Owl"] = {Huge = 99, Rainbow = 99},
        ["Deer"] = 6,
        ["Turtle"] = {Huge = 99, Rainbow = 99},
        ["Robin"] = 999,
        ["Bee"] = 999,
        ["Monkey"] = 999,
        ["Bear"] = 999,
        ["Golden Dragonfly"] = 999,
        ["Unicorn"] = 6,
        ["Raccoon"] = 999,
        ["Black Dragon"] = 999,
        ["Ice Serpent"] = 999,
    },

    ["Equip Pets"] = {
        {"Unicorn", 6, 1},
        {"Golden Dragonfly", 6, 2},
        {"Monkey", 6, 3},
        {"Deer", 6, 4},
        {"Bunny", 6, 5},
        {"Robin", 6, 6},
        {"Bee", 6, 7},
        {"Ice Serpent", 6, 8},
        {"Bear", 6, 9},
    },

    ["Expand Plot"] = true,
    ["Plot Expansions"] = 3,
    ["Unlock Pet Slots"] = 6,
    ["Auto Collect Seed Packs"] = true,

    ["Gears"] = {
        ["Buy Gear"] = {
            ["Common Watering Can"] = 5,
            ["Common Sprinkler"] = 5,
            ["Uncommon Sprinkler"] = 10,
            ["Rare Sprinkler"] = 10,
            ["Legendary Sprinkler"] = 10,
            ["Trowel"] = 5,
            ["Gnome"] = 10,
            ["Super Watering Can"] = 100,
            ["Super Sprinkler"] = 100,
            ["Strawberry Sniper"] = 10,
        },
        ["Gears To Use"] = {
            "Common Watering Can",
            "Common Sprinkler",
            "Uncommon Sprinkler",
            "Rare Sprinkler",
            "Legendary Sprinkler",
            "Super Watering Can",
            "Super Sprinkler",
        },
    },

    ["Webhook Pet URL"] = "https://discord.com/api/webhooks/1407998660377317467/cAvvNrsINeCckQw2Mavvi-QREkYmmgfYQMPxlazqA6nLLjTOFdQXNe0X8CkTux694fcn",
    ["Webhook Pet Name"] = {
        "Golden Dragonfly",
        "Unicorn",
        "Raccoon",
        "Monkey",
        "Bear",
        "Bee",
        "Ice Serpent",
        "Black Dragon",
    },
    ["Webhook Pet Rarity"] = {"Mythic", "Super", "Secret"},
    ["Webhook Seed URL"] = "https://discord.com/api/webhooks/1407998660377317467/cAvvNrsINeCckQw2Mavvi-QREkYmmgfYQMPxlazqA6nLLjTOFdQXNe0X8CkTux694fcn",
    ["Webhook Seed Name"] = {
        "Rainbow",
        "Gold",
        "Mega",
        "Dragon's Breath",
        "Hypno Bloom",
        "Moon Bloom",
        "Venom Spitter",
        "Poison Apple",
        "Pomegranate",
        "Venus Fly Trap",
        "Sunflower",
    },
    ["Webhook Gear URL"] = "https://discord.com/api/webhooks/1407998660377317467/cAvvNrsINeCckQw2Mavvi-QREkYmmgfYQMPxlazqA6nLLjTOFdQXNe0X8CkTux694fcn",
    ["Webhook Gear Name"] = {
        "Super Sprinkler",
        "Super Watering Can",
        "Strawberry Sniper",
    },
    ["Webhook Note"] = "TeoTest",
    ["Discord ID"] = "xxx",

    ["Mail To Username"] = {"XxJoolsBo3rxX98"},
    ["Items To Mail"] = {
        ["Pet"] = {
            ["Raccoon"] = {Normal = 2},
        },
        ["Seed"] = {
            ["Moon Bloom"] = 1,
            ["Hypno Bloom"] = 1,
        },
        ["Gear"] = {
            ["Super Watering Can"] = 1,
            ["Super Sprinkler"] = 1,
        },
    },

    ["Claim Mail"] = false,
}

loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/66adeacbfb46c0ea4883aefee367292a.lua"))()
