getgenv().UserConfig = {
    ["FPS Cap"] = 5,

    ["Auto Double Or Nothing"] = false,
    ["Double Or Nothing Target Wins"] = 1,

    ["Auto Buy Seed"] = true,
    ["Auto Plant Seed"] = true,
    ["Auto Plant"] = true,
    ["Limit Auto Plant"] = 300,

    ["Blacklist Seed"] = {
        "Rainbow",
        "Gold",
        "Mega",
    },

    ["Blacklist Shovel"] = {
        "Rainbow",
        "Gold",
        "Bloodlit",
        "Electric",
        "Starstruck",
        "Frozen",
        "Aurora",
        "Ignited",
        "Mushroom",
        "Dragon Fruit",
        "Dragon's Breath",
        "Hypno Bloom",
        "Moon Bloom",
        "Venom Spitter",
        "Poison Apple",
        "Pomegranate",
        "Venus Fly Trap",
        "Sunflower",
        "Cherry",
        "Acorn",
        "Ghost Pepper",
        "Briar Rose",
        "Romanesco",
        "Beanstalk",
        "Lotus",
        "Poison Ivy",
        "Glow Mushroom",
    },

    ["Shovel Plant Once"] = {
        "Carrot",
        "Strawberry",
        "Blueberry",
        "Tulip",
        "Tomato",
        "Apple",
    },

    ["Limit Plant Seed"] = {
        ["Carrot"] = 10,
        ["Strawberry"] = 20,
        ["Blueberry"] = 20,
        ["Tulip"] = 10,
        ["Tomato"] = 25,
        ["Apple"] = 20,
        ["Bamboo"] = 25,
        ["Corn"] = 30,
        ["Cactus"] = 30,
        ["Pineapple"] = 20,
        ["Mushroom"] = 3,
        ["Green Bean"] = 15,
        ["Banana"] = 25,
        ["Grape"] = 25,
        ["Coconut"] = 20,
        ["Mango"] = 25,
        ["Dragon Fruit"] = 60,
        ["Acorn"] = 80,
        ["Cherry"] = 80,
        ["Sunflower"] = 100,
        ["Venus Fly Trap"] = 120,
        ["Pomegranate"] = 120,
        ["Poison Apple"] = 120,
        ["Venom Spitter"] = 150,
        ["Moon Bloom"] = 200,
        ["Hypno Bloom"] = 200,
        ["Dragon's Breath"] = 200,
    },

    ["Limit Buy Seed"] = {
        ["Carrot"] = 20,
        ["Strawberry"] = 30,
        ["Blueberry"] = 30,
        ["Tulip"] = 20,
        ["Tomato"] = 40,
        ["Apple"] = 30,
        ["Bamboo"] = 60,
        ["Corn"] = 80,
        ["Cactus"] = 80,
        ["Pineapple"] = 50,
        ["Mushroom"] = 10,
        ["Green Bean"] = 40,
        ["Banana"] = 60,
        ["Grape"] = 60,
        ["Coconut"] = 40,
        ["Mango"] = 50,
        ["Dragon Fruit"] = 120,
        ["Acorn"] = 150,
        ["Cherry"] = 150,
        ["Sunflower"] = 200,
        ["Venus Fly Trap"] = 300,
        ["Pomegranate"] = 300,
        ["Poison Apple"] = 300,
        ["Venom Spitter"] = 500,
        ["Moon Bloom"] = 999,
        ["Hypno Bloom"] = 999,
        ["Dragon's Breath"] = 999,
    },

    ["Favorite"] = {
        ["Sunflower"] = {"Rainbow", "Bloodlit", "Starstruck", "Aurora", "Ignited"},
        ["Venus Fly Trap"] = {"Rainbow", "Bloodlit", "Starstruck", "Aurora", "Ignited"},
        ["Venom Spitter"] = {"Rainbow", "Bloodlit", "Starstruck", "Aurora", "Ignited"},
        ["Moon Bloom"] = {"Rainbow", "Bloodlit", "Starstruck", "Aurora", "Ignited"},
        ["Hypno Bloom"] = {"Rainbow", "Bloodlit", "Starstruck", "Aurora", "Ignited"},
        ["Dragon's Breath"] = {"Rainbow", "Bloodlit", "Starstruck", "Aurora", "Ignited"},
        ["Ghost Pepper"] = {"Rainbow", "Bloodlit", "Starstruck", "Aurora", "Ignited"},
        ["Lotus"] = {"Rainbow", "Bloodlit", "Starstruck", "Aurora", "Ignited"},
    },

    -- Harvest Mutation Only:
    --   {}: Harvest all plants normally.
    --   "PlantName": Only harvest that plant when it has any mutation.
    --   ["PlantName"] = {"Mutation1", "Mutation2"}:
    --       Only harvest that plant when it has one of the listed mutations.
    -- Plants not listed here are always harvested normally.
    -- Example:
    -- ["Harvest Mutation Only"] = {
    --     "Bamboo",
    --     ["Tomato"] = {"Rainbow", "Gold", "Electric"},
    --     "Apple",
    -- },
    ["Harvest Mutation Only"] = {},

    ["Buy Pets"] = {
        ["Owl"] = 1,
        ["Deer"] = 6,
        ["Turtle"] = 2,
        ["Robin"] = 3,
        ["Bee"] = 1,
        ["Monkey"] = 1,
        ["Golden Dragonfly"] = 1,
        ["Unicorn"] = 1,
        ["Black Dragon"] = 1,
        ["Ice Serpent"] = 1,
    },

    ["Equip Pets"] = {
        {"Unicorn", 6, 1},
        {"Golden Dragonfly", 6, 2},
        {"Monkey", 6, 3},
        {"Deer", 6, 4},
        {"Robin", 6, 5},
        {"Bee", 6, 6},
        {"Ice Serpent", 6, 7},
    },

    ["Expand Plot"] = true,
    ["Plot Expansions"] = 3,
    ["Unlock Pet Slots"] = 6,
    ["Auto Collect Seed Packs"] = true,

    ["Gears"] = {
        ["Buy Gear"] = {
            ["Common Watering Can"] = 5,
            ["Common Sprinkler"] = 5,
            ["Uncommon Sprinkler"] = 10,
            ["Rare Sprinkler"] = 10,
            ["Legendary Sprinkler"] = 10,
            ["Trowel"] = 5,
            ["Gnome"] = 10,
            ["Super Watering Can"] = 100,
            ["Super Sprinkler"] = 100,
            ["Strawberry Sniper"] = 10,
        },
        ["Gears To Use"] = {
            "Common Watering Can",
            "Common Sprinkler",
            "Uncommon Sprinkler",
            "Rare Sprinkler",
            "Legendary Sprinkler",
            "Super Watering Can",
            "Super Sprinkler",
        },
    },

    ["Webhook Pet URL"] = "https://discord.com/api/webhooks/1407998660377317467/cAvvNrsINeCckQw2Mavvi-QREkYmmgfYQMPxlazqA6nLLjTOFdQXNe0X8CkTux694fcn",
    ["Webhook Pet Name"] = {
        "Golden Dragonfly",
        "Unicorn",
        "Raccoon",
        "Monkey",
        "Bear",
        "Bee",
        "Ice Serpent",
        "Black Dragon",
    },
    ["Webhook Pet Rarity"] = {"Mythic", "Super", "Secret"},
    ["Webhook Seed URL"] = "https://discord.com/api/webhooks/1407998660377317467/cAvvNrsINeCckQw2Mavvi-QREkYmmgfYQMPxlazqA6nLLjTOFdQXNe0X8CkTux694fcn",
    ["Webhook Seed Name"] = {
        "Rainbow",
        "Gold",
        "Mega",
        "Dragon's Breath",
        "Hypno Bloom",
        "Moon Bloom",
        "Venom Spitter",
        "Poison Apple",
        "Pomegranate",
        "Venus Fly Trap",
        "Sunflower",
    },
    ["Webhook Gear URL"] = "https://discord.com/api/webhooks/1407998660377317467/cAvvNrsINeCckQw2Mavvi-QREkYmmgfYQMPxlazqA6nLLjTOFdQXNe0X8CkTux694fcn",
    ["Webhook Gear Name"] = {
        "Super Sprinkler",
        "Super Watering Can",
        "Strawberry Sniper",
    },
    ["Webhook Note"] = "TeoTest",
    ["Discord ID"] = "xxx",

    ["Mail To Username"] = {"XxJoolsBo3rxX98"},
    ["Items To Mail"] = {
        ["Pet"] = {
            ["Raccoon"] = 1,
        },
        ["Seed"] = {
            ["Moon Bloom"] = 1,
            ["Hypno Bloom"] = 1,
        },
        ["Gear"] = {
            ["Super Watering Can"] = 1,
            ["Super Sprinkler"] = 1,
            ["Strawberry Sniper"] = 1,
        },
    },

    ["Claim Mail"] = false,
}

loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/66adeacbfb46c0ea4883aefee367292a.lua"))()
